- name: Run the equivalent of "apt update" as a separate step
  apt:
    update_cache: yes
  become: yes
  become_method: sudo

- name: Run the equivalent of "apt upgrade" as a separate step
  apt:
    name: "*"
    state: latest
  become: yes
  become_method: sudo

- name: Run the equivalent of "apt autoremove" as a separate step
  apt:
    autoremove: yes
  become: yes
  become_method: sudo
