- name: Install docker-compose
  get_url:
    url : https://github.com/docker/compose/releases/download/1.25.0-rc2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'  
  become: yes
  become_method: sudo
