- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  become_method: sudo

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: yes
  become_method: sudo

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
  become: yes
  become_method: sudo

- name: Install Docker Module for Python
  pip:
    name: docker
  become: yes
  become_method: sudo

